# Travis-CI configuration file for Expr
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Heavily borrowed from SuperTuxKart's travis.yml.
#
# SuperTuxKart's travis.yml file can be found here:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# License: https://github.com/supertuxkart/stk-code/blob/master/COPYING
#

language: cpp
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

os:
  - linux

matrix:
  fast_finish: true

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-4.0"; fi

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build"
  - cd "build"
  - cmake ..
  - make VERBOSE=1 -j3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - g++-4.9
    - clang-4.0
    - cmake
    - build-essential

# EOF #
